// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWj0zWGYlhqXGB-Pn10-d5njN0-deFyT0',
    appId: '1:553065116660:web:05b85cebede286e8363fa1',
    messagingSenderId: '553065116660',
    projectId: 'f-study-buddy',
    authDomain: 'f-study-buddy.firebaseapp.com',
    storageBucket: 'f-study-buddy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhxrs16j2t1NXzklcpXizdHw3RXnoMXIc',
    appId: '1:553065116660:android:033e3f2d0e167bdf363fa1',
    messagingSenderId: '553065116660',
    projectId: 'f-study-buddy',
    storageBucket: 'f-study-buddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx3hJNZ3KnfKmCVf7IqMw1_npDILZ90zg',
    appId: '1:553065116660:ios:52bdba67a60aa283363fa1',
    messagingSenderId: '553065116660',
    projectId: 'f-study-buddy',
    storageBucket: 'f-study-buddy.firebasestorage.app',
    iosBundleId: 'com.example.fStudyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx3hJNZ3KnfKmCVf7IqMw1_npDILZ90zg',
    appId: '1:553065116660:ios:52bdba67a60aa283363fa1',
    messagingSenderId: '553065116660',
    projectId: 'f-study-buddy',
    storageBucket: 'f-study-buddy.firebasestorage.app',
    iosBundleId: 'com.example.fStudyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWj0zWGYlhqXGB-Pn10-d5njN0-deFyT0',
    appId: '1:553065116660:web:56b5a272629e1350363fa1',
    messagingSenderId: '553065116660',
    projectId: 'f-study-buddy',
    authDomain: 'f-study-buddy.firebaseapp.com',
    storageBucket: 'f-study-buddy.firebasestorage.app',
  );
}
